dryRun: false
outPath: "~/Downloads/Podcasts"
namespaceRegex: '(?:xmlns:(\S+)="(\S+)"[\s>])'
podList:
  - name: Office_Ladies
    rssFeedUrl: 'https://feeds.simplecast.com/PxEW_ipK'
    episodeUrlFilter: '(.*?)\?'

  - name: Celeritas
    rssFeedUrl: 'https://feeds.megaphone.fm/SBP2001311146'
    episodeUrlFilter: '(.*?)\?'
    artUrlFilter: '(.*?)\?'